.PHONY: run dbg

run:
	cd /data && LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/osmo-bsc -c osmo-bsc.cfg

dbg:
	cd /data && LD_LIBRARY_PATH=/usr/local/lib gdb --args /usr/local/bin/osmo-bsc -c osmo-bsc.cfg
