.PHONY: compile test log

default: compile
	$(MAKE) test; $(MAKE) log

compile:
	$(MAKE) -C /osmo-ttcn3-hacks hlr/compile
	$(MAKE) -C /osmo-ttcn3-hacks hlr -j

test:
	cd /data && \
		/osmo-ttcn3-hacks/start-testsuite.sh /osmo-ttcn3-hacks/hlr/HLR_Tests; \
		exit_code=$$?; \
		/osmo-ttcn3-hacks/log_merge.sh HLR_Tests --rm; \
		exit $$exit_code

log:
	cd /data; /osmo-ttcn3-hacks/log_merge.sh HLR_Tests --rm
